services:
  - type: web
    name: ecommerce-app
    env: node
    plan: free
    region: ohio
    buildCommand: |
      pnpm install
      cd server
      pnpm install
      pnpm run build
      cd ../client
      pnpm install
      pnpm run build
    startCommand: |
      cd server
      echo "Current directory:"
      pwd
      echo "Environment variables:"
      env | grep DB_
      echo "Starting server..."
      NODE_ENV=production node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_HOST
        fromService:
          type: mysql
          name: mysql-main
          property: host
      - key: DB_NAME
        value: ecommerce_db
      - key: DB_USER
        fromService:
          type: mysql
          name: mysql-main
          property: username
      - key: DB_PASSWORD
        fromService:
          type: mysql
          name: mysql-main
          property: password

  - type: mysql
    name: mysql-main
    plan: free
    ipAllowList: []  # Allow all IPs
    region: ohio
