services:
  - type: web
    name: ecommerce-app
    env: node
    plan: free
    buildCommand: |
      pnpm install
      cd server && pnpm install && rm -rf dist && pnpm run build
      cd ../client && pnpm install && pnpm run build
    startCommand: cd server && ls -la dist && NODE_ENV=production node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_HOST
        fromDatabase:
          name: ecommerce-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: ecommerce-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: ecommerce-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ecommerce-db
          property: password

databases:
  - name: ecommerce-db
    plan: free
    type: mysql
    version: "8"
