services:
  - type: web
    name: ecommerce-app
    env: node
    plan: free
    buildCommand: |
      pnpm install
            cd server
      pnpm install
      echo "Building server..."
      rm -rf dist
      npx tsc --project tsconfig.json
      ls -la dist
      cd ../client
      pnpm install
      pnpm run build
    startCommand: |
      cd server
      pwd
      ls -la
      ls -la dist || true
      NODE_ENV=production node dist/server.js
    startCommand: cd server && ls -la dist && NODE_ENV=production node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_HOST
        fromDatabase:
          name: ecommerce-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: ecommerce-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: ecommerce-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ecommerce-db
          property: password

databases:
  - name: ecommerce-db
    plan: free
    type: mysql
    version: "8"
